spring:
  application:
    name: QuartzDemo

  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DynamicScheduler
          threadPool:
            threadCount: 10
            threadPriority: 5

mybatis:
  mapper-locations: classpath:mapper/*.xml